# Generated by Django 4.2.11 on 2024-06-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Solteiru/a", "Solteiru/a"), ("Marridu/a", "Marridu/a")],
                max_length=10,
                null=True,
            ),
        ),
    ]
