# Generated by Django 4.2.11 on 2024-06-24 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0003_status_name"),
        ("cliente", "0008_rename_documentus_funcionariu_documentos_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GymClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("days_of_week", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nu_id", models.CharField(max_length=20, null=True, unique=True)),
                ("nome_completo", models.CharField(max_length=200, null=True)),
                (
                    "sexo",
                    models.CharField(
                        blank=True,
                        choices=[("Mane", "Mane"), ("Feto", "Feto")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("naturalidade", models.CharField(max_length=200, null=True)),
                ("data_do_nasc", models.DateField()),
                ("join_date", models.DateField(auto_now_add=True)),
                ("endereço", models.CharField(max_length=200, null=True)),
                ("nu_contacto", models.CharField(max_length=200, null=True)),
                ("email", models.EmailField(max_length=200, null=True)),
                (
                    "fotografia",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "documentos",
                    models.FileField(blank=True, null=True, upload_to="CV/"),
                ),
                (
                    "estatuto",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom.status",
                    ),
                ),
                (
                    "município",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="custom.municipality",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(name="Funcionariu",),
    ]
