# Generated by Django 4.2.11 on 2024-06-24 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0009_gymclass_member_delete_funcionariu"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gymclass", old_name="name", new_name="naran",
        ),
        migrations.RenameField(
            model_name="member", old_name="data_do_nasc", new_name="data_moris",
        ),
        migrations.RenameField(
            model_name="member", old_name="endereço", new_name="enderesu",
        ),
        migrations.RenameField(
            model_name="member", old_name="município", new_name="municipio",
        ),
        migrations.RenameField(
            model_name="member", old_name="nome_completo", new_name="naran",
        ),
        migrations.RenameField(
            model_name="member", old_name="nu_contacto", new_name="phone",
        ),
        migrations.RenameField(
            model_name="member", old_name="estatuto", new_name="status",
        ),
    ]
