# Generated by Django 4.2.11 on 2024-06-24 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0011_rename_naran_gymclass_name_enrollment"),
    ]

    operations = [
        migrations.RemoveField(model_name="member", name="status",),
    ]
