# Generated by Django 4.2.11 on 2024-06-25 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0004_delete_academiclevel"),
        ("cliente", "0017_member_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="enderesu",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="municipio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="custom.municipality",
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="naturalidade",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="custom.status",
            ),
        ),
    ]
