# Generated by Django 4.2.11 on 2024-06-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0018_alter_member_email_alter_member_enderesu_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gymclass",
            name="days_of_week",
            field=models.CharField(max_length=150),
        ),
    ]
