# Generated by Django 4.2.11 on 2024-06-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0019_alter_gymclass_days_of_week"),
    ]

    operations = [
        migrations.AddField(
            model_name="member", name="end_date", field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="member", name="data_moris", field=models.DateField(null=True),
        ),
    ]
