# Generated by Django 4.2.11 on 2024-06-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0020_member_end_date_alter_member_data_moris"),
    ]

    operations = [
        migrations.AddField(
            model_name="gymclass",
            name="payment_per_month",
            field=models.DecimalField(decimal_places=2, default=25.0, max_digits=6),
        ),
    ]
