# Generated by Django 4.2.11 on 2024-06-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cliente", "0021_gymclass_payment_per_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Marridu", "Marridu"), ("Solteiru", "Solteiru")],
                max_length=10,
                null=True,
            ),
        ),
    ]
