# Generated by Django 4.2.11 on 2024-06-26 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0006_status"),
        ("cliente", "0022_alter_member_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="status",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="custom.status",
            ),
        ),
    ]
