# Generated by Django 4.2.11 on 2024-06-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0004_delete_academiclevel"),
    ]

    operations = [
        migrations.DeleteModel(name="Status",),
    ]
