# Generated by Django 4.2.11 on 2024-06-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom", "0005_delete_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
